---
- name: check bash already configured
  stat:
    path: ~/.bash_profile
  register: "bash_profile"
  tags:
  - configuration
  
- name: Find out playbook's path
  shell: pwd
  register: playbook_path

- name: Bash script to remote
  copy:
    src: ./scripts/bash_profile.sh
    dest: '{{ playbook_path.stdout }}/bash_profile.sh'
    mode: '777'
  when: (not bash_profile.stat.exists)  
  
- name: Run and configure Bash Profile.
  shell: ./bash_profile.sh
  args:
    executable: /bin/bash
  changed_when: false
  when: (not bash_profile.stat.exists)  
    

- name: Delete copied script for bash configuration
  command:  bash -c "rm -rf '{{ playbook_path.stdout }}/bash_profile.sh'"
  when: (not bash_profile.stat.exists)  

